### PR TITLE
JS Native json

### PR DESCRIPTION
**Pull request by VsevolodZakharov**
This is 2 times faster with json/test/speed_test.flow
@alstrup , @ykuzmenko73 , please take a look

### CODE REVIEW

**Comment by alstrup** [comment]
How does it behave when you give it mal-formed JSON? I know our parseJson does not have any particular error recovery strategy, but worth just checking what happens in these cases.

**Comment by VsevolodZakharov** [comment]
It returns JsonDouble(0) when exception. Most cases doParseJson() does the same - for example for empty input string,

**Comment by alstrup** [comment]
OK, in that case, good with me.

**Comment by ykuzmenko73** [comment]
Checked the branch, it seems it 3-5 times faster that flow-base Json and does not make lot of work for GC

**Pull request merged**
