### PR TITLE
checking of the SW version, checking of the SW updates

### PR DESCRIPTION
**Pull request by MalkoVl**
Added SW versions check on SW registration.
Added listener for SW updates.
More info about SW in the console.
image
image
image

### CODE REVIEW

**Comment by alstrup** [comment]
Where do we reference sw.js? It sounds like those places should have a "sw.js?v2" URL or similar instead, so we avoid this entire thing and can force a reload.

**Comment by MalkoVl** [comment]
It's hardcoded on native: https://github.com/area9innovation/flow9/blob/master/platforms/js/ProgressiveWebTools.hx#L14
Not sure, but if we will register new SW (with new path) - it will be another SW and previouse cache will be lostю

**Comment by MalkoVl** [comment]
Also, Ivan has improved SW code by adding SW restart if new version detected (without app restart). For me, SW was restarted in about 4-5 minutes after application was loaded.

**Comment by MalkoVl** [comment]
@alstrup does we need it (mostly for investigating sw issues on remote servers) or Ivan's changes is enough?

**Comment by alstrup** [comment]
The simpler, the better. I can not evaluate if these changes help or not. If Ivan's changes are sufficient, then we do not need this.

**Comment by MalkoVl** [comment]
We decided to have it.

**Comment by alstrup** [comment]
Let us change the message to

"A component is updated. Please reload the application to apply it."

**Pull request merged**
