### PR TITLE
With feature fix

### PR DESCRIPTION
**Pull request by Coolrunner86**
Fixed multiple calls issue when source of "with" was a function call.

### CODE REVIEW

**Comment by Coolrunner86** [comment]
> Does it only introduce a local if it is not already a variable? If so, OK

Is it important? I thought it's not and should not impact performance of so.

**Comment by alstrup** [comment]
I think it matters but can come in a second improvement

**Comment by Coolrunner86** [comment]
> I think it matters but can come in a second improvement

Done

**Comment by alstrup** [comment]
ægtm

**Pull request merged**
