### PR TITLE
vscode: servers may be started/stopped manually

### PR DESCRIPTION
**Pull request by dmitry-vlasov**

### CODE REVIEW

**Comment by alstrup** [comment]
What is JS server?

**Comment by dmitry-vlasov** [comment]
JS server is LSP protocol implementation written inside flow extension. There are two variants of LSP:   an old one, written by Michael Pliskin inside the flow extension, and the new one, native flow implementation. Now a user may switch to one of these implementations by commands.

**Comment by alstrup** [comment]
Why have both?

**Comment by dmitry-vlasov** [comment]
I left an old implementation for reliability. This redundancy may be removed in future, when the new LSP server will be tested enough. If you insist, I can remove the old implementation in this PR.

**Comment by alstrup** [comment]
OK to keep it but call it legacy to help clarify. The new is default.

**Pull request merged**
