### PR TITLE
Introduced `setHttpRequestArgsUpdater` function

### PR DESCRIPTION
**Pull request by Eugeny48**
`setHttpRequestArgsUpdater` function can be used for:
1. Collecting requests (all, failed or successful);
2. Updating request parameters or headers;
3. Rejecting some requests;
4. Performing some requests on client side;

### CODE REVIEW

**Comment by Eugeny48** [comment]
[Demo mode for Application](https://trello.com/c/NbKWgLj6/1509-demo-mode-for-application)

**Review by bvaschenko — COMMENTED** [review]
Looks good to me. Just to be sure how it should be used: in case of demo mode we have to setHttpRequestArgsUpdater to
```
\args -> if (dbConnectorRequest(args) && readOnlyMode) {
    Some(args)
} else if (requestSupported(args)) {
    args.onData(preparedData);
    None();
} else {
    showRequestNotReadyWarning(args);
    None();
}
```
?
It looks like DW dbConnector requests are easy to distinguish by KeyValue("dbconnector", "true") parameter, what about MKS and interpreter dbConnector requests?

**Comment by Eugeny48** [comment]
> in case of demo mode we have to setHttpRequestArgsUpdater to ...
Yes it's like that. MKS we can detect by URL and operation, and all RIS requests are read-only.

**Review by bvaschenko — APPROVED** [review]
LGTM

**Pull request merged**
