### PR TITLE
for discussion : speed up getTreeValues

### PR DESCRIPTION
**Pull request by shkel**
curator_4

This PR speed up the fn, but there are 2 points to discuss here:
1) dlist2array is not good : dlist -> list -> array. (memory)
2) maybe a native Tree is better?

__
in PR:
dlist :
- make doDList2list tail recursive
- avoid garbage in doDList2list
- 
tree :
- attempt to improve getTreeValues

### CODE REVIEW

**Comment by alstrup** [comment]
DList has bigger footprint than List? Why is this better? Worth understanding better

**Comment by shkel** [comment]
> Why is this better? 

the reason is concat3
concat3(getTreeValues(left), [v], getTreeValues(right));

**Comment by shkel** [comment]
i merged the part about dlist, because it is not relevant to the discussion.

**Comment by alstrup** [comment]
Done in a simpler way using list2array and foldTree.

**Pull request closed without merging**
