### PR TITLE
HaxeRuntime: tune compareByValue in JS

### PR DESCRIPTION
**Pull request by ykuzmenko73**
In JS there is better way to compare that haxe generates. it produces too many garbage.

### CODE REVIEW

**Comment by ykuzmenko73** [comment]
[Large time difference when simulate two Readers](https://trello.com/c/OYvT8zlz/11141-large-time-difference-when-simulate-two-readers)

**Comment by alstrup** [comment]
In addition to objects (structs) and arrays, we also have refs and functions, which are also comparable. Are they still working as before?

**Comment by ykuzmenko73** [comment]
@alstrup , curator starts fine and shows reader fine too so I hope it works as before....

**Comment by ykuzmenko73** [comment]
The code was taken from the browser as generated code and put into untyped __js__ with small tweaks - garbage variables were removed, no other changes were maid

**Pull request closed without merging**
