### PR TITLE
Add Warning when a path in includes does not exist

### PR DESCRIPTION
**Pull request by magnusklundgren**

### CODE REVIEW

**Comment by alstrup** [comment]
We have the innovation path hardcoded in the flow compiler, but that does not make sense in the open source version. We would prefer not to have a warning for that one, and only complain about includes given by the user.

**Comment by magnusklundgren** [comment]
Changed to only include paths specified by the -I parameter

**Comment by alstrup** [comment]
Do we also check the includes from the flow.config file? That is important as well.

**Comment by magnusklundgren** [comment]
Yes. we check it now

**Comment by alstrup** [comment]
LGTM

**Pull request closed without merging**
