### PR TITLE
Add upload native file java native

### PR DESCRIPTION
**Pull request by dmitry-vlasov**

### CODE REVIEW

**Comment by alstrup** [comment]
Why not just add a default flow implementation? Is this required?

**Comment by dmitry-vlasov** [comment]
Serhii Mishchenko asked me to add a stub for this function. As I see, in order to implement it I need to implement a File native type and a bunch of corresponding functions from fs/filesystem.flow.

**Comment by alstrup** [comment]
We doubt we need it implemented. My point is that you can add a default flow implementation, and then there is no need for the native. However, this is OK.

**Comment by dmitry-vlasov** [comment]
It seems that this stub was put, but in the wrong native host: filesystem instead of http.

**Pull request merged**
