### PR TITLE
Escape pebble values

### PR DESCRIPTION
**Pull request by iv-menshenin**
https://trello.com/c/oyem9jV0/7072-communicator-screen-doesnt-render-correctly-as-you-click-through-the-messages

### CODE REVIEW

**Comment by iv-menshenin** [comment]
@bvaschenko Oops, sorry. I reverted changes for the binaries

**Comment by dmitrybure** [comment]
@bvaschenko don't you think having other special characters might cause problems with browsers? but it depends on how functions like `setUrlHash` are implemented

**Comment by bvaschenko** [comment]
> @bvaschenko don't you think having other special characters might cause problems with browsers? but it depends on how functions like `setUrlHash` are implemented

https://tools.ietf.org/html/rfc3986#section-3.5
It shouldn't cause any problem as URL-encoding is necessary for passing parameters to the server, but URL hash is used only at the client-side.

**Comment by dmitrybure** [comment]
OK, then let's try `escapePebbleParameterValue`

**Comment by bvaschenko** [comment]
https://github.com/area9innovation/flow9/commit/bb2144589cbbeb8854159f655d478c1722ae6a22

**Pull request closed without merging**
