### PR TITLE
Fix promises

### PR DESCRIPTION
**Pull request by yegordovganich**
Warning instead of assert, refactoring and small optimizations
- don't fire until all promises are done (either fulfilled or rejected)
- minor refactoring

### CODE REVIEW

**Comment by yegordovganich** [comment]
The problem that in master it crashes when the number of fulfill calls in one promise equals the number of promises - because there is only dull counter.
`promisesCrash = [
  Promise(\f, r -> timer(500, \ -> f(1))),
  Promise(\f, r -> {f(2); f(3)})
`
Timer in promise is an emulation of request to database. So assert crashes the app when f(3) is called. In the branch there is no crash, just waiting for the first promise and fires with [1, 3].

**Comment by shkel** [comment]
image

**Comment by yegordovganich** [comment]
@alstrup I know you are on phone, it's not urgent, but have a look when you have a time, pls

**Comment by alstrup** [comment]
Hard to review, but if tested OK

**Pull request merged**
