### PR TITLE
iOS: Implement metadata media stream scan for qr, etc. codes

### PR DESCRIPTION
**Pull request by vereschagai**

### CODE REVIEW

**Comment by alstrup** [comment]
lgtm. Is there a JS api for this kind of thing as well for PWA? We would love to use QR codes in Rhapsode for login for very small kids.

**Comment by vereschagai** [comment]
@alstrup That should be possible without big effort. Brief search and I found a library written in pure JS to determinate QR codes from ImageData, we grab from Camera: https://github.com/cozmo/jsQR.

**Comment by alstrup** [comment]
Would be great with an example app that did it in JS, but this can be merged before then as far as I'm concerned. We need QR for login for kids shortly.

**Comment by vereschagai** [comment]
> Would be great with an example app that did it in JS, but this can be merged before then as far as I'm concerned. We need QR for login for kids shortly.

The test js library app is here: https://cozmo.github.io/jsQR/.
OK, I am making JS implementation a priority.

**Pull request merged**
