### PR TITLE
JS: introduce cloneString fn and tune parseJson / deserializeRestOfStringTail

### PR DESCRIPTION
**Pull request by ykuzmenko73**
In Chrome, when we substring str then we get not new copy but sliced string
if we do many nested slices then we may got extremely long (1000+) slicing chain with size much more that total size of substrings.
it is especially true if we deserialize some recursive structure like Json
this fix breaks slicing on the Object and String level for Json.

checked with string to Json convertion with string size 42 Mb
in master the real size of Json is about 300 Mb, in the branch i is only 65 Mb
the parsing time reduced almost twice.

in the branch:
image

in the master:
image

loading http://localhost/rhapsode/flowjs.html?name=curator&new=1&server=qa#modules:

master: 13.5 sec, 392 Mb after GC

branch: 10 sec, 185 Mb after GC

### CODE REVIEW

**Comment by ykuzmenko73** [comment]
QtByteRunner rebuilt for linux, needed to be rebuilt for windows too

**Comment by alstrup** [comment]
Use fallback native implementation, instead of dummy implementation in all targets but JS/Haxe.

**Comment by ykuzmenko73** [comment]
fallback native implementation is used instead of CPP and others

**Comment by alstrup** [comment]
LGTM.

**Comment by ykuzmenko73** [comment]
[Investigate performance for curator based on prod data](https://trello.com/c/mC0Mhb5G/629-investigate-performance-for-curator-based-on-prod-data)

**Pull request merged**
